export class Sinistre {
    id: number;
    lieu: string;
    evaluation: any;
    employeur: any;
    dateDeces: any;
    lieuDeces: any;
    causeDeces: any;
    numConvention: any;
    numPolice: any;
    denominationContrat: any;
    effet: any;
    echeance: any;
    duree: any;
    capitalInitial: any;
    createdDate: any;
    createdBy: any;
    capitalRestant: any;
    typeSinistre: any;
    nomPrenomDeces: any;
    adressDeces: any;
    ageDeces: any;
    professionDeces: any;
    agenceReference: any;
    montantApayer: any;
    payer: any;
    beneficiaireId: any;
    sfdReference: any;
    clientId: any
}
