import { BaseEntity } from '../../shared';

export class CreditRequest implements BaseEntity {
  constructor(
    public id?: number,
    public client?: any,
    public produit?: any,
    public denomination?: string,
    public userReference?: string,
    public agenceReference?: string,
    public reference?: string,
    public requestDate?: any,
    public amount?: number,
    public duration?: number,
    public interestRate?: number,
    public nbrDiffere?: number,
    public createdDate?: any,
    public delaiGrace?: any,
    public createdBy?: string,
    public lastModifiedBy?: string,
    public userInitial?: string,
    public lastModifiedDate?: any,
    public clientLib?: string,
    public expressionRequest?: any,
    public etudes?: BaseEntity[],
    public dossiers?: BaseEntity[],
    public requestStatusId?: number,
    public requestObjectId?: number,
    public produitId?: number,
    public periodicityId?: number,
    public clientId?: number,
    public clientConditionNoteId?: number,
    public codePhase?: string,
  ) { }
}
