/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['ol.tabs[_ngcontent-%COMP%] {\n    background: transparent;\n    display: block;\n    width: 100%;\n    height: 20px;\n    text-align: center;\n    margin: 0px 2px 15px 0px;\n    text-decoration: none;\n}\n\nol[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    text-decoration: none;\n    outline: none;\n}\n\nol.tabs[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n    display: block;\n    width: 50%;\n    float: left;\n    cursor: pointer;\n}\n\n.tab1[_ngcontent-%COMP%] {\n    border-bottom: 3px solid deepskyblue;\n    border-bottom-right-radius: 5px;\n    border-bottom-left-radius: 5px;\n}\n\n.more[_ngcontent-%COMP%] {\n    display: none;\n    position: fixed;\n    top: 89px;\n    right: 7px;\n    width: 50px;\n    height: 50px;\n    border-radius: 50%;\n    background: blue;\n    cursor: pointer;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYW5kcmUvRG9jdW1lbnRzL3Byb2pldHNKSGlwc3Rlci9zZmQvc3JjL21haW4vd2ViYXBwL2FwcC9lbnRpdGllcy9yZW1ib3Vyc2VtZW50LXNmZC9yZW1ib3Vyc2VtZW50LXNmZC5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2FuZHJlL0RvY3VtZW50cy9wcm9qZXRzSkhpcHN0ZXIvc2ZkL3NyYy9tYWluL3dlYmFwcC9hcHAvZW50aXRpZXMvcmVtYm91cnNlbWVudC1zZmQvcmVtYm91cnNlbWVudC1zZmQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
