export * from './client.model';
export * from './client-popup.service';
export * from './client.service';
export * from './client-dialog.component';
export * from './client-delete-dialog.component';
export * from './client-detail.component';
export * from './client.component';
export * from './client.route';
export * from './client-indetification-sheet.component';
