import { BaseEntity } from '../../shared';

export class Client implements BaseEntity {
  constructor(
    public id?: number,
    public userReference?: string,
    public name?: string,
    public code?: string,
    public cpteCarmes?: string,
    public email?: string,
    public bp?: string,
    public fax?: string,
    public phone?: string,
    public birthDate?: any,
    public sex?: string,
    public birthPlace?: string,
    public conjointName?: string,
    public conjointPhone?: string,
    public pictureUrl?: string,
    public picture: any = '',
    public contactPersonName?: string,
    public contactPersonPhone?: string,
    public identityCard?: string,
    public fingerPrintLeft?: string,
    public fingerPrintRight?: string,
    public signature?: string,
    public commercialRegisterNumber?: string,
    public createdDate?: any,
    public createdBy?: string,
    public lastModifiedBy?: string,
    public lastModifiedDate?: any,
    public firstName?: string,
    public alias?: string,
    public denomination?: string,
    public ifus?: string,
    public maidenName?: string,
    public employee?: boolean,
    public apparente?: boolean,
    public motherName?: string,
    public fatherName?: string,
    public addressses?: BaseEntity[],
    public creditRequests?: BaseEntity[],
    public comptes?: BaseEntity[],
    public compensations?: BaseEntity[],
    public sfds?: BaseEntity[],
    public groupMembers?: BaseEntity[],
    public groups?: BaseEntity[],
    public agenceId?: number,
    public civilityId?: number,
    public situationMatId?: number,
    public idCarteTypeId?: number,
    public professionId?: number,
    public nationalityId?: number,
    public countryId?: number,
    public literacyId?: number,
    public schoolLevelId?: number,
    public typeClientId?: number,
    public leaderId?: number,
    public posteId?: number,
    public agenceReference?: string,
    public userInitial?: string,
    public produitId?: number,
    public status?: boolean | string,
    public depart?: boolean | string,
    public date_depart?: any,
    public ravip?: string,
    public recepisse?: string,
  ) {
    this.employee = false;
    this.apparente = false;
    // this.phone = '00229';
  }
}
